target("core")
  set_kind("static")
  add_headerfiles("src/core/*.h")
  add_headerfiles("src/file/*.h")
  add_headerfiles("src/core/*.hpp")
  add_headerfiles("src/assets/*.h")
  add_files("src/core/*.cpp")
  add_files("src/file/*.cpp")

target("cs")
    set_kind("binary")
    add_deps("core")
    add_files("src/cmd/run.cpp")

target("test")
  set_kind("binary")
  add_deps("core")
  add_files("test/test.cpp")
